#ifndef CEV_COLORS_H_INCLUDED
#define CEV_COLORS_H_INCLUDED

/**preset colors**/

#define CEV_COLOR_WHITE         (SDL_Color){0xFF, 0xFF, 0xFF, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BLACK         (SDL_Color){0x00, 0x00, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_GREY          (SDL_Color){0x80, 0x80, 0x80, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_GREYDARK      (SDL_Color){0x69, 0x69, 0x69, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_GREYLIGHT     (SDL_Color){0xD3, 0xD3, 0xD3, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_YELLOW        (SDL_Color){0xFF, 0xFF, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_YELLOWDARK    (SDL_Color){0xFF, 0xD7, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_YELLOWLIGHT   (SDL_Color){0xFF, 0xFF, 0xE0, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BLUE          (SDL_Color){0x00, 0x00, 0xFF, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BLUEDARK      (SDL_Color){0x00, 0x00, 0x80, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BLUELIGHT     (SDL_Color){0x87, 0xCE, 0xFA, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_RED           (SDL_Color){0xFF, 0x00, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_REDDARK       (SDL_Color){0x8B, 0x00, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_REDLIGHT      (SDL_Color){0xFA, 0x80, 0x72, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_GREEN         (SDL_Color){0x00, 0xFF, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_GREENDARK     (SDL_Color){0x00, 0x64, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_GREENLIGHT    (SDL_Color){0x98, 0xFB, 0x98, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_PINK          (SDL_Color){0xFF, 0x49, 0xB4, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_PURPLE        (SDL_Color){0xFF, 0x00, 0xFF, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_PURPLEDARK    (SDL_Color){0x8B, 0x00, 0x8B, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_PURPLELIGHT   (SDL_Color){0xDD, 0xA0, 0xDD, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_ORANGE        (SDL_Color){0xFF, 0xA5, 0x00, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BROWN         (SDL_Color){0xD2, 0x69, 0x1E, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BROWNDARK     (SDL_Color){0x8B, 0x45, 0x13, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_BROWNLIGHT    (SDL_Color){0xDA, 0xA5, 0x20, SDL_ALPHA_OPAQUE}

#define CEV_COLOR_TEXT CEV_COLOR_WHITE
#define CEV_COLOR_BACKGROUND    (SDL_Color){0x32, 0x32, 0x32, SDL_ALPHA_OPAQUE}
#define CEV_COLOR_SELECTED      (SDL_Color){0xB4, 0xB4, 0xB4, SDL_ALPHA_OPAQUE}












#endif // CEV_COLORS_H_INCLUDED
